version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    env_file:
    - ./backend/.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    env_file:
    - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Drake2713
      POSTGRES_DB: tfg
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    env_file:
      - ./backend/.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"

