version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      - postgres
      - rabbitmq
  
  server:
    build:
      context: ./dummy
    networks:
      - app_network
    depends_on:
      - backend
    volumes:
      - ./backend:/app/backend
    
  notificaciones_server:
    build:
      context: ./notificaciones
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - backend
  
  worker:
    build:
      context: .
      dockerfile: queueWorker/Dockerfile
    networks:
      - app_network
    depends_on:
      - backend
    volumes:
      - ./backend:/app/backend

  postgres:
    image: postgres:15
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Drake2713
      POSTGRES_DB: tfg
    ports:
      - "5432:5432"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
