"""init

Revision ID: 0f1e43da1c77
Revises: ae798f4139f8
Create Date: 2024-01-02 14:35:00.011244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1e43da1c77'
down_revision: Union[str, None] = 'ae798f4139f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_practicas_id', table_name='practicas')
    op.create_index(op.f('ix_practicas_id'), 'practicas', ['id'], unique=True)
    op.create_table('practicas_usuario',
    sa.Column('user_niub', sa.String(), nullable=False),
    sa.Column('practicas_id', sa.Integer(), nullable=False),
    sa.Column('corregit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['practicas_id'], ['practicas.id'], ),
    sa.ForeignKeyConstraint(['user_niub'], ['user.niub'], ),
    sa.PrimaryKeyConstraint('user_niub', 'practicas_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practicas_id'), table_name='practicas')
    op.create_index('ix_practicas_id', 'practicas', ['id'], unique=False)
    op.drop_table('practicas_usuario')
    # ### end Alembic commands ###
