"""init

Revision ID: 6b9ecbc843db
Revises: 
Create Date: 2023-12-03 17:58:16.494233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9ecbc843db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('descripcio', sa.String(), nullable=True))
    op.alter_column('cursos', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_niub', table_name='users')
    op.create_index(op.f('ix_users_niub'), 'users', ['niub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_niub'), table_name='users')
    op.create_index('ix_users_niub', 'users', ['niub'], unique=False)
    op.alter_column('cursos', 'nom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cursos', 'descripcio')
    # ### end Alembic commands ###
