"""init

Revision ID: 78e5899876b9
Revises: c1d2366a1a3f
Create Date: 2023-12-28 17:45:06.750476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e5899876b9'
down_revision: Union[str, None] = 'c1d2366a1a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_practicas_id', table_name='practicas')
    op.drop_table('practicas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('curs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripcio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idiomaP', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['curs'], ['cursos.id'], name='practicas_curs_fkey'),
    sa.PrimaryKeyConstraint('id', 'curs', 'nom', name='practicas_pkey')
    )
    op.create_index('ix_practicas_id', 'practicas', ['id'], unique=False)
    # ### end Alembic commands ###
