"""init

Revision ID: 8adc0f34e6dc
Revises: 78e5899876b9
Create Date: 2023-12-28 17:45:36.891397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adc0f34e6dc'
down_revision: Union[str, None] = '78e5899876b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curs', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('descripcio', sa.String(), nullable=True),
    sa.Column('idiomaP', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['curs'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id', 'nom')
    )
    op.create_index(op.f('ix_practicas_id'), 'practicas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practicas_id'), table_name='practicas')
    op.drop_table('practicas')
    # ### end Alembic commands ###
