"""Add pending_niubs column to course table

Revision ID: 93211d8cdaa5
Revises: eeea862d688e
Create Date: 2025-05-21 00:22:28.717383

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '93211d8cdaa5'
down_revision = 'eeea862d688e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('pending_niubs', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'pending_niubs')
    # ### end Alembic commands ###
