"""initial migration

Revision ID: 9e53ca14e150
Revises: 
Create Date: 2025-02-28 12:43:30.896663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e53ca14e150'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('curs', sa.String(), nullable=False),
    sa.Column('descripcio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('user',
    sa.Column('niub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('is_alumno', sa.Boolean(), nullable=True),
    sa.Column('is_profesor', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('niub'),
    sa.UniqueConstraint('niub')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('cursos_usuario',
    sa.Column('user_niub', sa.String(), nullable=False),
    sa.Column('cursos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cursos_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['user_niub'], ['user.niub'], ),
    sa.PrimaryKeyConstraint('user_niub', 'cursos_id')
    )
    op.create_table('practicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curs', sa.Integer(), nullable=True),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('descripcio', sa.String(), nullable=True),
    sa.Column('idiomaP', sa.String(), nullable=False),
    sa.Column('entrega', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['curs'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id', 'nom'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_practicas_id'), 'practicas', ['id'], unique=True)
    op.create_table('practicas_usuario',
    sa.Column('user_niub', sa.String(), nullable=False),
    sa.Column('practicas_id', sa.Integer(), nullable=False),
    sa.Column('corregit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['practicas_id'], ['practicas.id'], ),
    sa.ForeignKeyConstraint(['user_niub'], ['user.niub'], ),
    sa.PrimaryKeyConstraint('user_niub', 'practicas_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practicas_usuario')
    op.drop_index(op.f('ix_practicas_id'), table_name='practicas')
    op.drop_table('practicas')
    op.drop_table('cursos_usuario')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
