"""init

Revision ID: b3bcd184c727
Revises: 28561813ecd1
Create Date: 2023-12-03 23:13:09.231555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bcd184c727'
down_revision: Union[str, None] = '28561813ecd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignaturas_alumnos', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignaturas_alumnos', 'id')
    # ### end Alembic commands ###
