"""init

Revision ID: bc2621ddc1d0
Revises: 9a6f2bd58619
Create Date: 2023-12-03 23:27:30.820513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2621ddc1d0'
down_revision: Union[str, None] = '9a6f2bd58619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignaturas_alumnos')
    op.drop_constraint('cursos_profesor_fkey', 'cursos', type_='foreignkey')
    op.drop_column('cursos', 'profesor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('profesor', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('cursos_profesor_fkey', 'cursos', 'users', ['profesor'], ['niub'])
    op.create_table('assignaturas_alumnos',
    sa.Column('niub', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_assignatura', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_assignatura'], ['cursos.id'], name='assignaturas_alumnos_id_assignatura_fkey'),
    sa.ForeignKeyConstraint(['niub'], ['users.niub'], name='assignaturas_alumnos_niub_fkey'),
    sa.PrimaryKeyConstraint('niub', name='assignaturas_alumnos_pkey')
    )
    # ### end Alembic commands ###
