"""server

Revision ID: bd5a597cfd17
Revises: 0f1e43da1c77
Create Date: 2024-01-03 13:57:30.951755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5a597cfd17'
down_revision: Union[str, None] = '0f1e43da1c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practicas', 'curs',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practicas', 'curs',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
