"""init

Revision ID: eecebe5c67b8
Revises: 990fd1b8057a
Create Date: 2023-12-28 17:03:24.060856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecebe5c67b8'
down_revision: Union[str, None] = '990fd1b8057a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicas', sa.Column('descripcio', sa.String(), nullable=True))
    op.alter_column('practicas', 'curs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('practicas', 'Descripcio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicas', sa.Column('Descripcio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('practicas', 'curs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('practicas', 'descripcio')
    # ### end Alembic commands ###
