"""Add semester field to Course

Revision ID: eeea862d688e
Revises: c94f826165fe
Create Date: 2025-05-11 19:47:58.652865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeea862d688e'
down_revision = 'c94f826165fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TARDOR', 'PRIMAVERA', name='semesterenum').create(op.get_bind())
    op.add_column('course', sa.Column('semester', postgresql.ENUM('TARDOR', 'PRIMAVERA', name='semesterenum', create_type=False), server_default='TARDOR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'semester')
    sa.Enum('TARDOR', 'PRIMAVERA', name='semesterenum').drop(op.get_bind())
    # ### end Alembic commands ###
