name: Build and Deploy to Azure Web App (Container) Backend

on:
  push:
    branches:
      [ main ]
    paths:
    - 'backend/**'
    - '.github/workflows/deploy-backend.yml'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/golemxiv-backend:latest ./backend
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/golemxiv-backend:latest

    - name: Trigger Azure Web App Deployment Webhook
      run: |
        curl -X POST "${{ secrets.AZURE_WEBHOOK_URL_BACKEND }}"