name: Build and Deploy to Azure Container App Worker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'practice_correction_queue_worker/**'
    - '.github/workflows/deploy-practice-correction-queue-worker.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PRACTICECORRECTIONWORKERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRACTICECORRECTIONWORKERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRACTICECORRECTIONWORKERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./practice_correction_queue_worker
          dockerfilePath: Dockerfile
          registryUrl: golemxivbackend.azurecr.io
          registryUsername: ${{ secrets.PRACTICECORRECTIONWORKERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRACTICECORRECTIONWORKERAPP_REGISTRY_PASSWORD }}
          containerAppName: practice-correction-worker-app
          resourceGroup: GOLEM-XIV
          imageToBuild: golemxivbackend.azurecr.io/practice-correction-worker-app:${{ github.sha }}


